### ISSUE TITLE
Add Google buildings dataset tile for Rwanda

### ISSUE THREAD

**Issue by ivanzvonkov** [nasaharvest/crop-mask#90]
**Todo:**
- [ ] csv file can be downloaded here: https://sites.research.google/open-buildings/ 
- [ ] csv file needs to be filtered to just buildings with > 90% confidence 

**Guidelines:**
Can follow similar structure as [here](https://github.com/nasaharvest/crop-mask/blob/3126b89e8e76ce620bcd460a011db6291d61e2ee/src/datasets_labeled.py#L366)

**Final deliverable**:
- [ ] Validation metrics from retrained Rwanda model with new data
- [ ] Updated dvc files to ensure new data is stored remotely

**Comment by ivanzvonkov** [comment]
Closing due to inactivity
