### ISSUE TITLE
Add Rwanda parks datasets points

### ISSUE THREAD

**Issue by ivanzvonkov** [nasaharvest/crop-mask#93]
**Todo**
- [ ] Get shapefiles of parks
- [ ] Generate samples
- [ ] Create features from samples
- [ ] Retrain Rwanda model with new data

Final deliverable:
 - [ ] Validation metrics from retrained Rwanda model with new data
 - [ ] Updated dvc files to ensure new data is stored remotely

**Comment by ivanzvonkov** [comment]
Closing due to inactivity
